"Towers"
{   
     // --------------------------------------------------------------------------------
     // // List of all towers, their Recipes and components
     
     // Final secret tower is needing to be renamed as english translation was unknown
     
     // Type, Basic = Can be placed
     // Type, Advanced = Can only be combined
     // Type, Secret = Can only be one shot and will not show on the menu
     // OneShot, No = Can not be one shot
     // OneShot, Yes = Can be one shot
     // OneShot, Only = Can only be created through one shots
     // --------------------------------------------------------------------------------

     "gem_a1"
     {
          "Type" "Basic"
          "OneShot" "No"
          "MergesInto"
          {
               "Merge1" "gem_Asteriated_Ruby"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_a2"
               "Upgrade2" "gem_a3"
          }
     }
     
     "gem_d1"
     {
          "Type" "Basic"
          "OneShot" "No"
          "MergesInto"
          {
               "Merge1" "gem_Silver"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_d2"
               "Upgrade2" "gem_d3"
          }
     }
     
     "gem_e1"
     {
          "Type" "Basic"
          "OneShot" "No"
          "MergesInto"
          {
               "Merge1" "gem_Malachite"
          }
          "UpgradeInto"
          {
               "Upgrade1" "gem_e2"
               "Upgrade2" "gem_e3"
          }
     }
     
     "gem_o1"
     {
          "Type" "Basic"
          "OneShot" "No"
          "MergesInto"
          {
               "Merge1" "gem_Malachite"
               "Merge2" "gem_EHOME_Stone"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_o2"
               "Upgrade2" "gem_o3"
          }
     }
     
     "gem_q1"
     {
          "Type" "Basic"
          "OneShot" "No"
          "MergesInto"
          {
               "Merge1" "gem_Malachite"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_q2"
               "Upgrade2" "gem_q3"
          }
     }
     
     "gem_r1"
     {
          "Type" "Basic"
          "OneShot" "No"
          "MergesInto"
          {
               "Merge1" "gem_Asteriated_Ruby"
          }
          "UpgradeInto"
          {
               "Upgrade1" "gem_r2"
               "Upgrade2" "gem_r3"
          }
     }
     
     "gem_s1"
     {
          "Type" "Basic"
          "OneShot" "No"
          "MergesInto"
          {
               "Merge1" "gem_Silver"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_s2"
               "Upgrade2" "gem_s3"
          }
     }
     
     "gem_t1"
     {
          "Type" "Basic"
          "OneShot" "No"
          "MergesInto"
          {
               "Merge1" "gem_Silver"
          }
          "UpgradeInto"
          {
               "Upgrade1" "gem_t2"
               "Upgrade2" "gem_t3"
          }
     }
     
     "gem_a2"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Quartz"
          }
          "UpgradeInto"
          {
               "Upgrade1" "gem_a3"
               "Upgrade2" "gem_a4"
          }
          "Requirements"
          {
               "Recipe1" "gem_a1"
               "Recipe2" "gem_a1"
          }
     }
     
     "gem_d2"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Huge_Malachite"
               "Merge2" "gem_Gold"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_d3"
               "Upgrade2" "gem_d4"
          }
          "Requirements"
          {
               "Recipe1" "gem_d1"
               "Recipe2" "gem_d1"
          }
     }
     
     "gem_e2"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Paraiba_Tourmaline"
               "Merge2" "gem_Elaborately_Carved_Tourmaline"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_e3"
               "Upgrade2" "gem_e4"
          }
          "Requirements"
          {
               "Recipe1" "gem_e1"
               "Recipe2" "gem_e1"
          }
     }
     
     "gem_o2"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Uranium_238"
               "Merge2" "gem_Deep_Sea_Pearl"
               "Merge3" "gem_EHOME_Stone"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_o3"
               "Upgrade2" "gem_o4"
          }
          "Requirements"
          {
               "Recipe1" "gem_o1"
               "Recipe2" "gem_o1"
          }
     }
     
     "gem_q2"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Silver_Knight"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_q3"
               "Upgrade2" "gem_q4"
          }
          "Requirements"
          {
               "Recipe1" "gem_q1"
               "Recipe2" "gem_q1"
          }
     }
     
     "gem_r2"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Asteriated_Ruby"
               "Merge2" "gem_Antique_Bloodstone"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_r3"
               "Upgrade2" "gem_r4"
          }
          "Requirements"
          {
               "Recipe1" "gem_r1"
               "Recipe2" "gem_r1"
          }
     }
     
     "gem_s2"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Jade"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_s3"
               "Upgrade2" "gem_s4"
          }
          "Requirements"
          {
               "Recipe1" "gem_s1"
               "Recipe2" "gem_s1"
          }
     }
     
     "gem_t2"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Charming_Lazurite"
               "Merge2" "gem_Dark_Emerald"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_t3"
               "Upgrade2" "gem_t4"
          }
          "Requirements"
          {
               "Recipe1" "gem_t1"
               "Recipe2" "gem_t1"
          }
     }

     "gem_a3"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Volcano"
               "Merge2" "gem_Bloodstone"
          }
          "UpgradeInto"
          {
               "Upgrade1" "gem_a4"
               "Upgrade2" "gem_a5"
          }
          "Requirements"
          {
                "Process1"
                {
                    "Recipe1" "gem_a1"
                    "Recipe2" "gem_a1"
                    "Recipe3" "gem_a1"
                    "Recipe4" "gem_a1"
                }
                "Process2"
                {
                    "Recipe1" "gem_a2"
                    "Recipe2" "gem_a2"
                }
          }
     }
     
     "gem_d3"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Emerald_Golum"
               "Merge2" "gem_Pink_Diamond"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_d4"
               "Upgrade2" "gem_d5"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_d1"
                    "Recipe2" "gem_d1"
                    "Recipe3" "gem_d1"
                    "Recipe4" "gem_d1"
               }
               "Process2"
               {
                    "Recipe1" "gem_d2"
                    "Recipe2" "gem_d2"
               }
          }
     }
     
     "gem_e3"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Jade"
               "Merge2" "gem_Lucky_Chinese_Jade"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_e4"
               "Upgrade2" "gem_e5"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_e1"
                    "Recipe2" "gem_e1"
                    "Recipe3" "gem_e1"
                    "Recipe4" "gem_e1"
               }
               "Process2"
               {
                    "Recipe1" "gem_e2"
                    "Recipe2" "gem_e2"
               }
          }
     }
     
     "gem_o3"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Jade"
               "Merge2" "gem_EHOME_Stone"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_o4"
               "Upgrade2" "gem_o5"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_o1"
                    "Recipe2" "gem_o1"
                    "Recipe3" "gem_o1"
                    "Recipe4" "gem_o1"
               }
               "Process2"
               {
                    "Recipe1" "gem_o2"
                    "Recipe2" "gem_o2"
               }
          }
     }
     
     "gem_q3"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Grey_Jade"
               "Merge2" "gem_Egypt_Gold"
               "Merge3" "Chrysoberyl_Cat's_Eye"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_q4"
               "Upgrade2" "gem_q5"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_q1"
                    "Recipe2" "gem_q1"
                    "Recipe3" "gem_q1"
                    "Recipe4" "gem_q1"
               }
               "Process2"
               {
                    "Recipe1" "gem_q2"
                    "Recipe2" "gem_q2"
               }
          }
     }
     
     "gem_r3"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Silver_Knight"
               "Merge2" "gem_Quartz"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_r4"
               "Upgrade2" "gem_r5"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_r1"
                    "Recipe2" "gem_r1"
                    "Recipe3" "gem_r1"
                    "Recipe4" "gem_r1"
               }
               "Process2"
               {
                    "Recipe1" "gem_r2"
                    "Recipe2" "gem_r2"
               }
          }
     }
     
     "gem_s3"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Uranium_238"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_s4"
               "Upgrade2" "gem_s5"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_s1"
                    "Recipe2" "gem_s1"
                    "Recipe3" "gem_s1"
                    "Recipe4" "gem_s1"
               }
               "Process2"
               {
                    "Recipe1" "gem_s2"
                    "Recipe2" "gem_s2"
               }
          }
     }
     
     "gem_t3"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Huge_Malachite"
               "Merge2" "gem_Pink_Diamond"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_t4"
               "Upgrade2" "gem_t5"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_t1"
                    "Recipe2" "gem_t1"
                    "Recipe3" "gem_t1"
                    "Recipe4" "gem_t1"
               }
               "Process2"
               {
                    "Recipe1" "gem_t2"
                    "Recipe2" "gem_t2"
               }
          }
     }

     "gem_a4"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Charming_Lazurite"
               "Merge2" "gem_Gold"
               "Merge3" "gem_************"
          }
          "UpgradeInto"
          {
               "Upgrade1" "gem_a5"
               "Upgrade2" "gem_a6"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_a2"
                    "Recipe2" "gem_a2"
                    "Recipe3" "gem_a2"
                    "Recipe4" "gem_a2"
               }
               "Process2"
               {
                    "Recipe1" "gem_a3"
                    "Recipe2" "gem_a3"
               }
          }
     }
     
     "gem_d4"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Chrysoberyl_Cat's_Eye"
               "Merge2" "gem_Deep_Sea_Pearl"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_d5"
               "Upgrade2" "gem_d6"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_d2"
                    "Recipe2" "gem_d2"
                    "Recipe3" "gem_d2"
                    "Recipe4" "gem_d2"
               }
               "Process2"
               {
                    "Recipe1" "gem_d3"
                    "Recipe2" "gem_d3"
               }
          }
     }
     
     "gem_e4"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Quartz"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_e5"
               "Upgrade2" "gem_e6"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_e2"
                    "Recipe2" "gem_e2"
                    "Recipe3" "gem_e2"
                    "Recipe4" "gem_e2"
               }
               "Process2"
               {
                    "Recipe1" "gem_e3"
                    "Recipe2" "gem_e3"
               }
          }
     }
     
     "gem_o4"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Red_Coral"
               "Merge2" "gem_Paraiba_Tourmaline"
               "Merge3" "gem_EHOME_Stone"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_o5"
               "Upgrade2" "gem_o6"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_o2"
                    "Recipe2" "gem_o2"
                    "Recipe3" "gem_o2"
                    "Recipe4" "gem_o2"
               }
               "Process2"
               {
                    "Recipe1" "gem_o3"
                    "Recipe2" "gem_o3"
               }
          }
     }
     
     "gem_q4"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Bloodstone"
               "Merge2" "gem_Deep_Sea_Pearl"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_q5"
               "Upgrade2" "gem_q6"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_q2"
                    "Recipe2" "gem_q2"
                    "Recipe3" "gem_q2"
                    "Recipe4" "gem_q2"
               }
               "Process2"
               {
                    "Recipe1" "gem_q3"
                    "Recipe2" "gem_q3"
               }
          }
     }
     
     "gem_r4"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Volcano"
               "Merge2" "gem_Yellow_Sapphire"
               "Merge3" "gem_************"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_r5"
               "Upgrade2" "gem_r6"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_r2"
                    "Recipe2" "gem_r2"
                    "Recipe3" "gem_r2"
                    "Recipe4" "gem_r2"
               }
               "Process2"
               {
                    "Recipe1" "gem_r3"
                    "Recipe2" "gem_r3"
               }
          }
     }
     
     "gem_s4"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Grey_Jade"
               "Merge2" "gem_Dark_Emerald"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_s5"
               "Upgrade2" "gem_s6"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_s2"
                    "Recipe2" "gem_s2"
                    "Recipe3" "gem_s2"
                    "Recipe4" "gem_s2"
               }
               "Process2"
               {
                    "Recipe1" "gem_s3"
                    "Recipe2" "gem_s3"
               }
          }
     }
     
     "gem_t4"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Yellow_Sapphire"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_t5"
               "Upgrade2" "gem_t6"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_t2"
                    "Recipe2" "gem_t2"
                    "Recipe3" "gem_t2"
                    "Recipe4" "gem_t2"
               }
               "Process2"
               {
                    "Recipe1" "gem_t3"
                    "Recipe2" "gem_t3"
               }
          }
     }     
     
     "gem_a5"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Gold"
               "Merge2" "gem_Eygpt_Gold"
               "Merge3" "gem_************"
          }
          "UpgradeInto"
          {
               "Upgrade1" "gem_a6"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_a3"
                    "Recipe2" "gem_a3"
                    "Recipe3" "gem_a3"
                    "Recipe4" "gem_a3"
               }
               "Process2"
               {
                    "Recipe1" "gem_a4"
                    "Recipe2" "gem_a4"
               }
          }
     }
     
     "gem_d5"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Pink_Diamond"
               "Merge2" "gem_Obsidian"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_d6"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_d3"
                    "Recipe2" "gem_d3"
                    "Recipe3" "gem_d3"
                    "Recipe4" "gem_d3"
               }
               "Process2"
               {
                    "Recipe1" "gem_d4"
                    "Recipe2" "gem_d4"
               }
          }
     }
     
     "gem_e5"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Dark_Emerald"
               "Merge2" "gem_Agate"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_e6"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_e3"
                    "Recipe2" "gem_e3"
                    "Recipe3" "gem_e3"
                    "Recipe4" "gem_e3"
               }
               "Process2"
               {
                    "Recipe1" "gem_e4"
                    "Recipe2" "gem_e4"
               }
          }
     }
     
     "gem_o5"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Chrysoberyl_Cat's_Eye"
               "Merge2" "gem_EHOME_Stone"
               "Merge3" "gem_Agate"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_o6"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_o3"
                    "Recipe2" "gem_o3"
                    "Recipe3" "gem_o3"
                    "Recipe4" "gem_o3"
               }
               "Process2"
               {
                    "Recipe1" "gem_o4"
                    "Recipe2" "gem_o4"
               }
          }
     }
     
     "gem_q5"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Paraiba_Tourmaline"
               "Merge2" "gem_Agate"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_q6"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_q3"
                    "Recipe2" "gem_q3"
                    "Recipe3" "gem_q3"
                    "Recipe4" "gem_q3"
               }
               "Process2"
               {
                    "Recipe1" "gem_q4"
                    "Recipe2" "gem_q4"
               }
          }
     }
     
     "gem_r5"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Bloodstone"
               "Merge2" "gem_************"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_r6"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_r3"
                    "Recipe2" "gem_r3"
                    "Recipe3" "gem_r3"
                    "Recipe4" "gem_r3"
               }
               "Process2"
               {
                    "Recipe1" "gem_r4"
                    "Recipe2" "gem_r4"
               }
          }
     }
     
     "gem_s5"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Yellow_Sapphire"
               "Merge2" "gem_Obsidian"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_s6"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_s3"
                    "Recipe2" "gem_s3"
                    "Recipe3" "gem_s3"
                    "Recipe4" "gem_s3"
               }
               "Process2"
               {
                    "Recipe1" "gem_s4"
                    "Recipe2" "gem_s4"
               }
          }
     }
     
     "gem_t5"
     {
          "Type" "Basic"
          "OneShot" "Yes"
          "MergesInto"
          {
               "Merge1" "gem_Uranium_238"
               "Merge2" "gem_Obsidian"
          } 
          "UpgradeInto"
          {
               "Upgrade1" "gem_t6"
          }
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_t3"
                    "Recipe2" "gem_t3"
                    "Recipe3" "gem_t3"
                    "Recipe4" "gem_t3"
               }
               "Process2"
               {
                    "Recipe1" "gem_t4"
                    "Recipe2" "gem_t4"
               }
          }
     }
          
     "gem_Silver"
     {   
          "Type" "Advanced"
          "OneShot" "Yes"
          "Requirements"
          {
               "Recipe1" "gem_d1"
               "Recipe2" "gem_s1"
               "Recipe3" "gem_t1"
          }
     }

     "gem_Silver_Knight"
     {
          "Type" "Advanced"
          "OneShot" "No"
          "Requirements"
          {
               "Recipe1" "gem_Silver"
               "Recipe2" "gem_q2"
               "Recipe3" "gem_r3"
          }
     }
     
     "gem_Malachite"
     {   
          "Type" "Advanced"
          "OneShot" "Yes"
          "Requirements"
          {
               "Recipe1" "gem_e1"
               "Recipe2" "gem_o1"
               "Recipe3" "gem_q1"
          }
    }
         
    "gem_Huge_Malachite"
    {
          "Type" "Advanced"
          "OneShot" "No"
          "Requirements"
          {
               "Recipe1" "gem_Malachite"
               "Recipe2" "gem_d2"
               "Recipe3" "gem_t3"
            }
    }


     "gem_Asteriated_Ruby"
     {
          "Type" "Advanced"
          "OneShot" "Yes"
          "Requirements"
          {
               "Recipe1" "gem_r2"
               "Recipe2" "gem_r1"
               "Recipe3" "gem_a1"
          }
     }

     "gem_Volcano"
     {
          "Type" "Advanced"
          "OneShot" "No"
          "Requirements"
          {
               "Recipe1" "gem_Asteriated_Ruby"
               "Recipe2" "gem_r4"
               "Recipe3" "gem_a3"
          }
     }
     
     "gem_Quartz"
     {
          "Type" "Advanced"
          "OneShot" "Yes"
          "Requirements"
          {
               "Recipe1" "gem_e4"
               "Recipe2" "gem_r3"
               "Recipe3" "gem_a2"
          }
     }
     
     "gem_Charming_Lazurite"
     {
          "Type" "Advanced"
          "OneShot" "No"
          "Requirements"
          {
               "Recipe1" "gem_Quartz"
               "Recipe2" "gem_a4"
               "Recipe3" "gem_t2"
          }
     }
     
     "gem_Jade"
     {
          "Type" "Advanced"
          "OneShot" "Yes"
          "Requirements"
          {
               "Recipe1" "gem_e3"
               "Recipe2" "gem_o3"
               "Recipe3" "gem_s2"
          }
     }     
     
     "gem_Lucky_Chinese_Jade"
     {
          "Type" "Advanced"
          "OneShot" "No"
          "Requirements"
          {
               "Recipe1" "gem_Jade"
               "Recipe2" "gem_Quartz"
               "Recipe3" "gem_e3"
          }
     }     
     
     "gem_Grey_Jade"
     {
          "Type" "Advanced"
          "OneShot" "No"
          "Requirements"
          {
               "Recipe1" "gem_Jade"
               "Recipe2" "gem_s4"
               "Recipe3" "gem_q3"
          }
     }     
     
     "gem_Dark_Emerald"
     {
          "Type" "Advanced"
          "OneShot" "Yes"
          "Requirements"
          {
               "Recipe1" "gem_e5"
               "Recipe2" "gem_s4"
               "Recipe3" "gem_t2"
          }
     }     
     
     "gem_Emerald_Golem"
     {
          "Type" "Advanced"
          "OneShot" "No"
          "Requirements"
          {
               "Recipe1" "gem_Gold"
               "Recipe2" "gem_Dark_Emerald"
               "Recipe3" "gem_d3"
          }
     }     
     
     "gem_Yellow_Sapphire"
     {
          "Type" "Advanced"
          "OneShot" "Yes"
          "Requirements"
          {
               "Recipe1" "gem_s5"
               "Recipe2" "gem_t4"
               "Recipe3" "gem_r4"
          }
     }     
     
     "gem_Gold"
     {
          "Type" "Advanced"
          "OneShot" "Yes"
          "Requirements"
          {
               "Recipe1" "gem_a5"
               "Recipe2" "gem_a4"
               "Recipe3" "gem_d2"
          }
     }     
     
     "gem_Egypt_Gold"
     {
          "Type" "Advanced"
          "OneShot" "No"
          "Requirements"
          {
               "Recipe1" "gem_Gold"
               "Recipe2" "gem_a5"
               "Recipe3" "gem_q3"
          }
     }     
     
     "gem_Pink_Diamond"
     {
          "Type" "Advanced"
          "OneShot" "Yes"
          "Requirements"
          {
               "Recipe1" "gem_d5"
               "Recipe2" "gem_d3"
               "Recipe3" "gem_t3"
          }
     }     
     
     "gem_Huge_Pink_Diamond"
     {
          "Type" "Advanced"
          "OneShot" "No"
          "Requirements"
          {
               "Recipe1" "gem_Pink_Diamond"
               "Recipe2" "gem_Silver_Knight"
               "Recipe3" "gem_Silver"
          }
     }    
     
     "gem_Bloodstone"
     {
          "Type" "Advanced"
          "OneShot" "Yes"
          "Requirements"
          {
               "Recipe1" "gem_r5"
               "Recipe2" "gem_q4"
               "Recipe3" "gem_a3"
          }
     }     
     
     "gem_Antique_Bloodstone"
     {
          "Type" "Advanced"
          "OneShot" "No"
          "Requirements"
          {
               "Recipe1" "gem_Bloodstone"
               "Recipe2" "gem_Volcano"
               "Recipe3" "gem_r2"
          }
     }     
     
     "gem_Uranium_238"
     {
          "Type" "Advanced"
          "OneShot" "Yes"
          "Requirements"
          {
               "Recipe1" "gem_t5"
               "Recipe2" "gem_s3"
               "Recipe3" "gem_o2"
          }
     }     
     
     "gem_Uranium_235"
     {
          "Type" "Advanced"
          "OneShot" "No"
          "Requirements"
          {
               "Recipe1" "gem_Uranium_238"
               "Recipe2" "gem_Huge_Malachite"
               "Recipe3" "gem_Malachite"
          }
     }     
     
     "gem_Chrysoberyl_Cat's_Eye"
     {
          "Type" "Advanced"
          "OneShot" "Yes"
          "Requirements"
          {
               "Recipe1" "gem_o5"
               "Recipe2" "gem_d4"
               "Recipe3" "gem_q3"
          }
     }     
     
     "gem_Red_Coral"
     {
          "Type" "Advanced"
          "OneShot" "No"
          "Requirements"
          {
               "Recipe1" "gem_Chrysoberyl_Cat's_Eye"
               "Recipe2" "gem_Deep_Sea_Pearl"
               "Recipe3" "gem_o4"
          }
     }     
     
     "gem_Paraiba_Tourmaline"
     {
          "Type" "Advanced"
          "OneShot" "Yes"
          "Requirements"
          {
               "Recipe1" "gem_q5"
               "Recipe2" "gem_o4"
               "Recipe3" "gem_e2"
          }
     }     
     
     "gem_Elaborately_Carved_Tourmaline"
     {
          "Type" "Advanced"
          "OneShot" "No"
          "Requirements"
          {
               "Recipe1" "gem_Paraiba_Tourmaline"
               "Recipe2" "gem_Dark_Emerald"
               "Recipe3" "gem_e2"
          }
     }     
     
     "gem_Deep_Sea_Pearl"
     {
          "Type" "Advanced"
          "OneShot" "Yes"
          "Requirements"
          {
               "Recipe1" "gem_q4"
               "Recipe2" "gem_d4"
               "Recipe3" "gem_o2"
          }
     }
     
          "gem_a6"
     {
          "Type" "Advanced"
          "OneShot" "Only"
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_a4"
                    "Recipe2" "gem_a4"
                    "Recipe3" "gem_a4"
                    "Recipe4" "gem_a4"
               }
               "Process2"
               {
                    "Recipe1" "gem_a5"
                    "Recipe2" "gem_a5"
               }
          }
     }
     
     "gem_d6"
     {
          "Type" "Advanced"
          "OneShot" "Only"
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_d4"
                    "Recipe2" "gem_d4"
                    "Recipe3" "gem_d4"
                    "Recipe4" "gem_d4"
               }
               "Process2"
               {
                    "Recipe1" "gem_d5"
                    "Recipe2" "gem_d5"
               }
          }
     }
     
     "gem_e6"
     {
          "Type" "Advanced"
          "OneShot" "Only"
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_e4"
                    "Recipe2" "gem_e4"
                    "Recipe3" "gem_e4"
                    "Recipe4" "gem_e4"
               }
               "Process2"
               {
                    "Recipe1" "gem_e5"
                    "Recipe2" "gem_e5"
               }
          }
     }
     
     "gem_o6"
     {
          "Type" "Advanced"
          "OneShot" "Only"
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_o4"
                    "Recipe2" "gem_o4"
                    "Recipe3" "gem_o4"
                    "Recipe4" "gem_o4"
               }
               "Process2"
               {
                    "Recipe1" "gem_o5"
                    "Recipe2" "gem_o5"
               }
          }
     }
     
     "gem_q6"
     {
          "Type" "Advanced"
          "OneShot" "Only"
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_q4"
                    "Recipe2" "gem_q4"
                    "Recipe3" "gem_q4"
                    "Recipe4" "gem_q4"
               }
               "Process2"
               {
                    "Recipe1" "gem_q5"
                    "Recipe2" "gem_q5"
               }
          }
     }
     
     "gem_r6"
     {
          "Type" "Advanced"
          "OneShot" "Only"
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_r4"
                    "Recipe2" "gem_r4"
                    "Recipe3" "gem_r4"
                    "Recipe4" "gem_r4"
               }
               "Process2"
               {
                    "Recipe1" "gem_r5"
                    "Recipe2" "gem_r5"
               }
          }
     }
     
     "gem_s6"
     {
          "Type" "Advanced"
          "OneShot" "Only"
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_s4"
                    "Recipe2" "gem_s4"
                    "Recipe3" "gem_s4"
                    "Recipe4" "gem_s4"
               }
               "Process2"
               {
                    "Recipe1" "gem_s5"
                    "Recipe2" "gem_s5"
               }
          }
     }
     
     "gem_t6"
     {
          "Type" "Advanced"
          "OneShot" "Only"
          "Requirements"
          {
               "Process1"
               {
                    "Recipe1" "gem_t4"
                    "Recipe2" "gem_t4"
                    "Recipe3" "gem_t4"
                    "Recipe4" "gem_t4"
               }
               "Process2"
               {
                    "Recipe1" "gem_t5"
                    "Recipe2" "gem_t5"
               }
          }
     }
     
     "gem_EHOME_Stone"
     {
          "Type" "Secret"
          "OneShot" "Only"
          "Requirements"
          {
               "Recipe1" "gem_o1"
               "Recipe2" "gem_o2"
               "Recipe3" "gem_o3"
               "Recipe4" "gem_o4"
               "Recipe5" "gem_o5"
          }
     }
     
     "gem_Obsidian"
     {
          "Type" "Secret"
          "OneShot" "Only"
          "Requirements"
          {
               "Recipe1" "gem_d5"
               "Recipe2" "gem_s5"
               "Recipe3" "gem_t5"
          }
     }
     
     "gem_Agate"
     {
          "Type" "Secret"
          "OneShot" "Only"
          "Requirements"
          {
               "Recipe1" "gem_e5"
               "Recipe2" "gem_o5"
               "Recipe3" "gem_q5"
          }
     }
     
     "gem_************"
     {
          "Type" "Secret"
          "OneShot" "Only"
          "Requirements"
          {
               "Recipe1" "gem_r5"
               "Recipe2" "gem_a5"
               "Recipe3" "gem_r4"
               "Recipe4" "gem_a4"
          }
     }
}
