"Towers"
{   

     "gem_a1"
    {   
        "Damage" "1"
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Flame_Ruby"

        } 
        
    }
    "gem_d1"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Silver"

        } 
    }
    "gem_e1"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Malachite"

        } 
    }
    "gem_o1"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Malachite"

        } 
    }
    "gem_q1"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Malachite"
        } 
    }
    "gem_r1"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Flame_Ruby"
           

        } 
        
    }
    "gem_s1"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Silver"

        } 
    }
    "gem_t1"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Silver"

        } 
        
    }
     "gem_a2"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Quartz"

        } 
        
    }
    "gem_d2"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Huge_Malachite"
            
            

        } 
    }
    "gem_e2"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Paraiba_Tourmaline"
            "Merge2" "gem_Elaborately_Carved_Tourmaline"

        } 
    }
    "gem_o2"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Uranium_238"
            "Merge2" "gem_DeepSea_Pearl"

        } 
    }
    "gem_q2"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Silver_Knight"
            

        } 
    }
    "gem_r2"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Flame_Ruby"
           "Merge2" "gem_Antique_Bloodstone"

        } 
        
    }
    "gem_s2"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Jade"

        } 
    }
    "gem_t2"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Charming_Lazurite"
            "Merge2" "gem_Dark_Emerald"
        } 
        
    }

     "gem_a3"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Volcano"
            "Merge2" "gem_Bloodstone"

        } 
        
    }
    "gem_d3"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Pink_Diamond"
            "Merge2" "gem_Emerald_Golem"

        } 
    }
    "gem_e3"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Jade"
            "Merge2" "gem_Lucky_Chinese_Jade"
        } 
    }
    "gem_o3"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Jade"
            

        } 
    }
    "gem_q3"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Chrysoberyl_Cats_Eye"
            "Merge2" "gem_Egypt_Gold"
        } 
    }
    "gem_r3"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Silver_Knight"
            "Merge2" "gem_Quartz"
        } 
        
    }
    "gem_s3"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Uranium_238"
            "Merge2" "gem_Grey_Jade"

        } 
    }
    "gem_t3"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Huge_Malachite"
            "Merge2" "gem_Pink_Diamond"

        } 
        
    }


    "gem_a4"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Gold"
            "Merge2" "gem_Charming_Lazurite"
        }       
    }

    "gem_d4"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Chrysoberyl_Cats_Eye"
            "Merge2" "gem_DeepSea_Pearl"
        } 
    }

    "gem_e4"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Quartz"
        } 
    }

    "gem_o4"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Paraiba_Tourmaline"
            "Merge2" "gem_Red_Coral"
        } 
    }

    "gem_q4"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_DeepSea_Pearl"
            "Merge2" "gem_Bloodstone"
        } 
    }

    "gem_r4"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Volcano"
            "Merge2" "gem_Yellow_Sapphire"
        } 
        
    }

    "gem_s4"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Dark_Emerald"
            "Merge2" "gem_Grey_Jade"
        } 
    }

    "gem_t4"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Yellow_Sapphire"

        } 
    }

    "gem_a5"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Gold"
            "Merge2" "gem_Egypt_Gold"
        }       
    }

    "gem_d5"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Pink_Diamond"
        } 
    }

    "gem_e5"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Dark_Emerald"
        } 
    }

    "gem_o5"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Chrysoberyl_Cats_Eye"
        } 
    }

    "gem_q5"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Paraiba_Tourmaline"
        } 
    }

    "gem_r5"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Bloodstone"
        } 
        
    }

    "gem_s5"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Yellow_Sapphire"
        } 
    }

    "gem_t5"
    {
        "Type" "Basic"
        "MergesInto"
        {
            "Merge1" "gem_Uranium_238"
        } 
    }

    "gem_a6"
    {
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Null"
        }     
    }

    "gem_d6"
    {
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Null"
        }       
    }

    "gem_e6"
    {
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Null"
        }       
    }

    "gem_o6"
    {
        "Type" "Advanced" 
        "MergesInto"
        {
            "Merge1" "gem_Null"
        }      
    }

    "gem_q6"
    {
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Null"
        }      
    }

    "gem_r6"
    {
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Null"
        }   
    }

    "gem_s6"
    {
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Null"
        }        
    }

    "gem_t6"
    {
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Null"
        }        
    }


    "gem_Silver"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Silver_Knight"
            "Merge2" "gem_Huge_Pink_Diamond"
        }
        "Requirements"
        {   
            "Count" "3"
            "1" "gem_d1"
            "2" "gem_s1"
            "3" "gem_t1"
        }
    }

    "gem_Malachite"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Huge_Malachite"
            "Merge2" "gem_Uranium_235"
        }
        "Requirements"
        {
            "Count" "3"
            "1" "gem_e1"
            "2" "gem_o1"
            "3" "gem_q1"
        }
    }

    "gem_Flame_Ruby"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Volcano"
        }        
        "Requirements"
        {   
            "Count" "3"
            "1" "gem_a1"
            "2" "gem_r1"
            "3" "gem_r2"
        }
    }

    "gem_Silver_Knight"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Huge_Pink_Diamond"
        }
        "Requirements"
        {   
            "Count" "3"
            "1" "gem_Silver"
            "2" "gem_q2"
            "3" "gem_r3"
        }
    }

    "gem_Huge_Malachite"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Uranium_235"
        }
        "Requirements"
        {
            "Count" "3"
            "1" "gem_Malachite"
            "2" "gem_d2"
            "3" "gem_t3"
        }
    }

    "gem_Volcano"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Antique_Bloodstone"
        }
        "Requirements"
        {
            "Count" "3"
            "1" "gem_Flame_Ruby"
            "2" "gem_r4"
            "3" "gem_a3"
        }
    }

    "gem_Quartz"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Charming_Lazurite"
        }
        "Requirements"
        {
            "Count" "3"
            "1" "gem_e4"
            "2" "gem_r3"
            "3" "gem_a2"
        }
    }

    "gem_Charming_Lazurite"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Null"
        }   
        "Requirements"
        {
            "Count" "3"
            "1" "gem_Quartz"
            "2" "gem_a4"
            "3" "gem_t2"
        }
    }

    "gem_Jade"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Grey_Jade"
            "Merge2" "gem_Lucky_Chinese_Jade"
        }
        "Requirements"
        {
            "Count" "3"
            "1" "gem_e3"
            "2" "gem_o3"
            "3" "gem_s2"
        }
    }

    "gem_Lucky_Chinese_Jade"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Null"
        }   
        "Requirements"
        {
            "Count" "3"
            "1" "gem_Jade"
            "2" "gem_Quartz"
            "3" "gem_e3"
        }
    }

    "gem_Grey_Jade"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Null"
        }   
        "Requirements"
        {
            "Count" "3"
            "1" "gem_Jade"
            "2" "gem_s4"
            "3" "gem_s3"
        }
    }

    "gem_Dark_Emerald"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Emerald_Golem"
            "Merge2" "gem_Elaborately_Carved_Tourmaline"
        }
        "Requirements"
        {
            "Count" "3"
            "1" "gem_e5"
            "2" "gem_s4"
            "3" "gem_t2"
        }
    }

    "gem_Emerald_Golem"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Null"
        }   
        "Requirements"
        {
            "Count" "3"
            "1" "gem_Gold"
            "2" "gem_Dark_Emerald"
            "3" "gem_d3"
        }
    }

    "gem_Yellow_Sapphire"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Null"
        }   
        "Requirements"
        {
            "Count" "3"
            "1" "gem_s5"
            "2" "gem_t4"
            "3" "gem_r4"
        }
    }

    "gem_Gold"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Egypt_Gold"
            "Merge2" "gem_Emerald_Golem"
        }
        "Requirements"
        {
            "Count" "3"
            "1" "gem_a5"
            "2" "gem_a4"
            "3" "gem_d2"
        }
    }

    "gem_Egypt_Gold"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Null"
        }   
        "Requirements"
        {
            "Count" "3"
            "1" "gem_Gold"
            "2" "gem_a5"
            "3" "gem_q3"
        }
    }

    "gem_Pink_Diamond"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Huge_Pink_Diamond"
        }
        "Requirements"
        {
            "Count" "3"
            "1" "gem_d5"
            "2" "gem_d3"
            "3" "gem_t3"
        }
    }

    "gem_Huge_Pink_Diamond"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Null"
        }   
        "Requirements"
        {
            "Count" "3"
            "1" "gem_Pink_Diamond"
            "2" "gem_Silver_Knight"
            "3" "gem_Silver"
        }
    }

    "gem_Bloodstone"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Antique_Bloodstone"
        }
        "Requirements"
        {
            "Count" "3"
            "1" "gem_r5"
            "2" "gem_q4"
            "3" "gem_a3"
        }
    }

    "gem_Antique_Bloodstone"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Null"
        }   
        "Requirements"
        {
            "Count" "3"
            "1" "gem_Bloodstone"
            "2" "gem_Volcano"
            "3" "gem_r2"
        }
    }

    "gem_Uranium_238"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Uranium_235"
        }
        "Requirements"
        {
            "Count" "3"
            "1" "gem_t5"
            "2" "gem_s3"
            "3" "gem_o2"
        }
    }

    "gem_Uranium_235"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Null"
        }   
        "Requirements"
        {
            "Count" "3"
            "1" "gem_Uranium_238"
            "2" "gem_Huge_Malachite"
            "3" "gem_Malachite"
        }
    }

    "gem_Chrysoberyl_Cats_Eye"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Red_Coral"
        }
        "Requirements"
        {
            "Count" "3"
            "1" "gem_o5"
            "2" "gem_d4"
            "3" "gem_q3"
        }
    }

    "gem_DeepSea_Pearl"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Red_Coral"
        }
        "Requirements"
        {
            "Count" "3"
            "1" "gem_q4"
            "2" "gem_d4"
            "3" "gem_o2"
        }
    }

    "gem_Red_Coral"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Null"
        }   
        "Requirements"
        {
            "Count" "3"
            "1" "gem_Chrysoberyl_Cats_Eye"
            "2" "gem_DeepSea_Pearl"
            "3" "gem_o4"
        }
    }

    "gem_Paraiba_Tourmaline"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Elaborately_Carved_Tourmaline"
        }
        "Requirements"
        {
            "Count" "3"
            "1" "gem_q5"
            "2" "gem_o4"
            "3" "gem_e2"
        }
    }

    "gem_Elaborately_Carved_Tourmaline"
    {   
        "Type" "Advanced"
        "MergesInto"
        {
            "Merge1" "gem_Null"
        }   
        "Requirements"
        {
            "Count" "3"
            "1" "gem_Paraiba_Tourmaline"
            "2" "gem_Dark_Emerald"
            "3" "gem_e2"
        }
    }
    "gem_Null"
    {
        "Type"  "Advanced"
        "Requirements"
        {
            "Count" "3"
            "1" "gem_Null"
            "2" "gem_Null"
            "3" "gem_Null"
        }
    }  
}